package com.snsoft.dao.entities;

public class Acode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.acode
     *
     * @mbg.generated
     */
    private String acode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.aname
     *
     * @mbg.generated
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.shortcode
     *
     * @mbg.generated
     */
    private String shortcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.dc
     *
     * @mbg.generated
     */
    private Short dc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.vdclimit
     *
     * @mbg.generated
     */
    private Short vdclimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.property
     *
     * @mbg.generated
     */
    private Integer property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.fcode
     *
     * @mbg.generated
     */
    private String fcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.ymdeprecated
     *
     * @mbg.generated
     */
    private Integer ymdeprecated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.levl
     *
     * @mbg.generated
     */
    private Byte levl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.codelevl
     *
     * @mbg.generated
     */
    private String codelevl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.flags
     *
     * @mbg.generated
     */
    private Short flags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.langname1
     *
     * @mbg.generated
     */
    private String langname1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.langname2
     *
     * @mbg.generated
     */
    private String langname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acode.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.acode
     *
     * @return the value of acode.acode
     *
     * @mbg.generated
     */
    public String getAcode() {
        return acode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.acode
     *
     * @param acode the value for acode.acode
     *
     * @mbg.generated
     */
    public void setAcode(String acode) {
        this.acode = acode == null ? null : acode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.aname
     *
     * @return the value of acode.aname
     *
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.aname
     *
     * @param aname the value for acode.aname
     *
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.shortcode
     *
     * @return the value of acode.shortcode
     *
     * @mbg.generated
     */
    public String getShortcode() {
        return shortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.shortcode
     *
     * @param shortcode the value for acode.shortcode
     *
     * @mbg.generated
     */
    public void setShortcode(String shortcode) {
        this.shortcode = shortcode == null ? null : shortcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.type
     *
     * @return the value of acode.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.type
     *
     * @param type the value for acode.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.dc
     *
     * @return the value of acode.dc
     *
     * @mbg.generated
     */
    public Short getDc() {
        return dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.dc
     *
     * @param dc the value for acode.dc
     *
     * @mbg.generated
     */
    public void setDc(Short dc) {
        this.dc = dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.vdclimit
     *
     * @return the value of acode.vdclimit
     *
     * @mbg.generated
     */
    public Short getVdclimit() {
        return vdclimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.vdclimit
     *
     * @param vdclimit the value for acode.vdclimit
     *
     * @mbg.generated
     */
    public void setVdclimit(Short vdclimit) {
        this.vdclimit = vdclimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.property
     *
     * @return the value of acode.property
     *
     * @mbg.generated
     */
    public Integer getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.property
     *
     * @param property the value for acode.property
     *
     * @mbg.generated
     */
    public void setProperty(Integer property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.fcode
     *
     * @return the value of acode.fcode
     *
     * @mbg.generated
     */
    public String getFcode() {
        return fcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.fcode
     *
     * @param fcode the value for acode.fcode
     *
     * @mbg.generated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.ymdeprecated
     *
     * @return the value of acode.ymdeprecated
     *
     * @mbg.generated
     */
    public Integer getYmdeprecated() {
        return ymdeprecated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.ymdeprecated
     *
     * @param ymdeprecated the value for acode.ymdeprecated
     *
     * @mbg.generated
     */
    public void setYmdeprecated(Integer ymdeprecated) {
        this.ymdeprecated = ymdeprecated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.levl
     *
     * @return the value of acode.levl
     *
     * @mbg.generated
     */
    public Byte getLevl() {
        return levl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.levl
     *
     * @param levl the value for acode.levl
     *
     * @mbg.generated
     */
    public void setLevl(Byte levl) {
        this.levl = levl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.codelevl
     *
     * @return the value of acode.codelevl
     *
     * @mbg.generated
     */
    public String getCodelevl() {
        return codelevl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.codelevl
     *
     * @param codelevl the value for acode.codelevl
     *
     * @mbg.generated
     */
    public void setCodelevl(String codelevl) {
        this.codelevl = codelevl == null ? null : codelevl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.flags
     *
     * @return the value of acode.flags
     *
     * @mbg.generated
     */
    public Short getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.flags
     *
     * @param flags the value for acode.flags
     *
     * @mbg.generated
     */
    public void setFlags(Short flags) {
        this.flags = flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.langname1
     *
     * @return the value of acode.langname1
     *
     * @mbg.generated
     */
    public String getLangname1() {
        return langname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.langname1
     *
     * @param langname1 the value for acode.langname1
     *
     * @mbg.generated
     */
    public void setLangname1(String langname1) {
        this.langname1 = langname1 == null ? null : langname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.langname2
     *
     * @return the value of acode.langname2
     *
     * @mbg.generated
     */
    public String getLangname2() {
        return langname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.langname2
     *
     * @param langname2 the value for acode.langname2
     *
     * @mbg.generated
     */
    public void setLangname2(String langname2) {
        this.langname2 = langname2 == null ? null : langname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acode.bank
     *
     * @return the value of acode.bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acode.bank
     *
     * @param bank the value for acode.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }
}