package com.snsoft.dao.entities;

import java.util.ArrayList;
import java.util.List;

public class AcodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acode
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acode
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acode
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public AcodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acode
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAcodeIsNull() {
            addCriterion("acode is null");
            return (Criteria) this;
        }

        public Criteria andAcodeIsNotNull() {
            addCriterion("acode is not null");
            return (Criteria) this;
        }

        public Criteria andAcodeEqualTo(String value) {
            addCriterion("acode =", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeNotEqualTo(String value) {
            addCriterion("acode <>", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeGreaterThan(String value) {
            addCriterion("acode >", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeGreaterThanOrEqualTo(String value) {
            addCriterion("acode >=", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeLessThan(String value) {
            addCriterion("acode <", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeLessThanOrEqualTo(String value) {
            addCriterion("acode <=", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeLike(String value) {
            addCriterion("acode like", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeNotLike(String value) {
            addCriterion("acode not like", value, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeIn(List<String> values) {
            addCriterion("acode in", values, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeNotIn(List<String> values) {
            addCriterion("acode not in", values, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeBetween(String value1, String value2) {
            addCriterion("acode between", value1, value2, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeNotBetween(String value1, String value2) {
            addCriterion("acode not between", value1, value2, "acode");
            return (Criteria) this;
        }

        public Criteria andAnameIsNull() {
            addCriterion("aname is null");
            return (Criteria) this;
        }

        public Criteria andAnameIsNotNull() {
            addCriterion("aname is not null");
            return (Criteria) this;
        }

        public Criteria andAnameEqualTo(String value) {
            addCriterion("aname =", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotEqualTo(String value) {
            addCriterion("aname <>", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameGreaterThan(String value) {
            addCriterion("aname >", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameGreaterThanOrEqualTo(String value) {
            addCriterion("aname >=", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLessThan(String value) {
            addCriterion("aname <", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLessThanOrEqualTo(String value) {
            addCriterion("aname <=", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLike(String value) {
            addCriterion("aname like", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotLike(String value) {
            addCriterion("aname not like", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameIn(List<String> values) {
            addCriterion("aname in", values, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotIn(List<String> values) {
            addCriterion("aname not in", values, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameBetween(String value1, String value2) {
            addCriterion("aname between", value1, value2, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotBetween(String value1, String value2) {
            addCriterion("aname not between", value1, value2, "aname");
            return (Criteria) this;
        }

        public Criteria andShortcodeIsNull() {
            addCriterion("shortcode is null");
            return (Criteria) this;
        }

        public Criteria andShortcodeIsNotNull() {
            addCriterion("shortcode is not null");
            return (Criteria) this;
        }

        public Criteria andShortcodeEqualTo(String value) {
            addCriterion("shortcode =", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeNotEqualTo(String value) {
            addCriterion("shortcode <>", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeGreaterThan(String value) {
            addCriterion("shortcode >", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeGreaterThanOrEqualTo(String value) {
            addCriterion("shortcode >=", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeLessThan(String value) {
            addCriterion("shortcode <", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeLessThanOrEqualTo(String value) {
            addCriterion("shortcode <=", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeLike(String value) {
            addCriterion("shortcode like", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeNotLike(String value) {
            addCriterion("shortcode not like", value, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeIn(List<String> values) {
            addCriterion("shortcode in", values, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeNotIn(List<String> values) {
            addCriterion("shortcode not in", values, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeBetween(String value1, String value2) {
            addCriterion("shortcode between", value1, value2, "shortcode");
            return (Criteria) this;
        }

        public Criteria andShortcodeNotBetween(String value1, String value2) {
            addCriterion("shortcode not between", value1, value2, "shortcode");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDcIsNull() {
            addCriterion("dc is null");
            return (Criteria) this;
        }

        public Criteria andDcIsNotNull() {
            addCriterion("dc is not null");
            return (Criteria) this;
        }

        public Criteria andDcEqualTo(Short value) {
            addCriterion("dc =", value, "dc");
            return (Criteria) this;
        }

        public Criteria andDcNotEqualTo(Short value) {
            addCriterion("dc <>", value, "dc");
            return (Criteria) this;
        }

        public Criteria andDcGreaterThan(Short value) {
            addCriterion("dc >", value, "dc");
            return (Criteria) this;
        }

        public Criteria andDcGreaterThanOrEqualTo(Short value) {
            addCriterion("dc >=", value, "dc");
            return (Criteria) this;
        }

        public Criteria andDcLessThan(Short value) {
            addCriterion("dc <", value, "dc");
            return (Criteria) this;
        }

        public Criteria andDcLessThanOrEqualTo(Short value) {
            addCriterion("dc <=", value, "dc");
            return (Criteria) this;
        }

        public Criteria andDcIn(List<Short> values) {
            addCriterion("dc in", values, "dc");
            return (Criteria) this;
        }

        public Criteria andDcNotIn(List<Short> values) {
            addCriterion("dc not in", values, "dc");
            return (Criteria) this;
        }

        public Criteria andDcBetween(Short value1, Short value2) {
            addCriterion("dc between", value1, value2, "dc");
            return (Criteria) this;
        }

        public Criteria andDcNotBetween(Short value1, Short value2) {
            addCriterion("dc not between", value1, value2, "dc");
            return (Criteria) this;
        }

        public Criteria andVdclimitIsNull() {
            addCriterion("vdclimit is null");
            return (Criteria) this;
        }

        public Criteria andVdclimitIsNotNull() {
            addCriterion("vdclimit is not null");
            return (Criteria) this;
        }

        public Criteria andVdclimitEqualTo(Short value) {
            addCriterion("vdclimit =", value, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitNotEqualTo(Short value) {
            addCriterion("vdclimit <>", value, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitGreaterThan(Short value) {
            addCriterion("vdclimit >", value, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitGreaterThanOrEqualTo(Short value) {
            addCriterion("vdclimit >=", value, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitLessThan(Short value) {
            addCriterion("vdclimit <", value, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitLessThanOrEqualTo(Short value) {
            addCriterion("vdclimit <=", value, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitIn(List<Short> values) {
            addCriterion("vdclimit in", values, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitNotIn(List<Short> values) {
            addCriterion("vdclimit not in", values, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitBetween(Short value1, Short value2) {
            addCriterion("vdclimit between", value1, value2, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andVdclimitNotBetween(Short value1, Short value2) {
            addCriterion("vdclimit not between", value1, value2, "vdclimit");
            return (Criteria) this;
        }

        public Criteria andPropertyIsNull() {
            addCriterion("property is null");
            return (Criteria) this;
        }

        public Criteria andPropertyIsNotNull() {
            addCriterion("property is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyEqualTo(Integer value) {
            addCriterion("property =", value, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyNotEqualTo(Integer value) {
            addCriterion("property <>", value, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyGreaterThan(Integer value) {
            addCriterion("property >", value, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyGreaterThanOrEqualTo(Integer value) {
            addCriterion("property >=", value, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyLessThan(Integer value) {
            addCriterion("property <", value, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyLessThanOrEqualTo(Integer value) {
            addCriterion("property <=", value, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyIn(List<Integer> values) {
            addCriterion("property in", values, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyNotIn(List<Integer> values) {
            addCriterion("property not in", values, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyBetween(Integer value1, Integer value2) {
            addCriterion("property between", value1, value2, "property");
            return (Criteria) this;
        }

        public Criteria andPropertyNotBetween(Integer value1, Integer value2) {
            addCriterion("property not between", value1, value2, "property");
            return (Criteria) this;
        }

        public Criteria andFcodeIsNull() {
            addCriterion("fcode is null");
            return (Criteria) this;
        }

        public Criteria andFcodeIsNotNull() {
            addCriterion("fcode is not null");
            return (Criteria) this;
        }

        public Criteria andFcodeEqualTo(String value) {
            addCriterion("fcode =", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotEqualTo(String value) {
            addCriterion("fcode <>", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeGreaterThan(String value) {
            addCriterion("fcode >", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeGreaterThanOrEqualTo(String value) {
            addCriterion("fcode >=", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeLessThan(String value) {
            addCriterion("fcode <", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeLessThanOrEqualTo(String value) {
            addCriterion("fcode <=", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeLike(String value) {
            addCriterion("fcode like", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotLike(String value) {
            addCriterion("fcode not like", value, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeIn(List<String> values) {
            addCriterion("fcode in", values, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotIn(List<String> values) {
            addCriterion("fcode not in", values, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeBetween(String value1, String value2) {
            addCriterion("fcode between", value1, value2, "fcode");
            return (Criteria) this;
        }

        public Criteria andFcodeNotBetween(String value1, String value2) {
            addCriterion("fcode not between", value1, value2, "fcode");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedIsNull() {
            addCriterion("ymdeprecated is null");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedIsNotNull() {
            addCriterion("ymdeprecated is not null");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedEqualTo(Integer value) {
            addCriterion("ymdeprecated =", value, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedNotEqualTo(Integer value) {
            addCriterion("ymdeprecated <>", value, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedGreaterThan(Integer value) {
            addCriterion("ymdeprecated >", value, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedGreaterThanOrEqualTo(Integer value) {
            addCriterion("ymdeprecated >=", value, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedLessThan(Integer value) {
            addCriterion("ymdeprecated <", value, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedLessThanOrEqualTo(Integer value) {
            addCriterion("ymdeprecated <=", value, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedIn(List<Integer> values) {
            addCriterion("ymdeprecated in", values, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedNotIn(List<Integer> values) {
            addCriterion("ymdeprecated not in", values, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedBetween(Integer value1, Integer value2) {
            addCriterion("ymdeprecated between", value1, value2, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andYmdeprecatedNotBetween(Integer value1, Integer value2) {
            addCriterion("ymdeprecated not between", value1, value2, "ymdeprecated");
            return (Criteria) this;
        }

        public Criteria andLevlIsNull() {
            addCriterion("levl is null");
            return (Criteria) this;
        }

        public Criteria andLevlIsNotNull() {
            addCriterion("levl is not null");
            return (Criteria) this;
        }

        public Criteria andLevlEqualTo(Byte value) {
            addCriterion("levl =", value, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlNotEqualTo(Byte value) {
            addCriterion("levl <>", value, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlGreaterThan(Byte value) {
            addCriterion("levl >", value, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlGreaterThanOrEqualTo(Byte value) {
            addCriterion("levl >=", value, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlLessThan(Byte value) {
            addCriterion("levl <", value, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlLessThanOrEqualTo(Byte value) {
            addCriterion("levl <=", value, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlIn(List<Byte> values) {
            addCriterion("levl in", values, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlNotIn(List<Byte> values) {
            addCriterion("levl not in", values, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlBetween(Byte value1, Byte value2) {
            addCriterion("levl between", value1, value2, "levl");
            return (Criteria) this;
        }

        public Criteria andLevlNotBetween(Byte value1, Byte value2) {
            addCriterion("levl not between", value1, value2, "levl");
            return (Criteria) this;
        }

        public Criteria andCodelevlIsNull() {
            addCriterion("codelevl is null");
            return (Criteria) this;
        }

        public Criteria andCodelevlIsNotNull() {
            addCriterion("codelevl is not null");
            return (Criteria) this;
        }

        public Criteria andCodelevlEqualTo(String value) {
            addCriterion("codelevl =", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlNotEqualTo(String value) {
            addCriterion("codelevl <>", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlGreaterThan(String value) {
            addCriterion("codelevl >", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlGreaterThanOrEqualTo(String value) {
            addCriterion("codelevl >=", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlLessThan(String value) {
            addCriterion("codelevl <", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlLessThanOrEqualTo(String value) {
            addCriterion("codelevl <=", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlLike(String value) {
            addCriterion("codelevl like", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlNotLike(String value) {
            addCriterion("codelevl not like", value, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlIn(List<String> values) {
            addCriterion("codelevl in", values, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlNotIn(List<String> values) {
            addCriterion("codelevl not in", values, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlBetween(String value1, String value2) {
            addCriterion("codelevl between", value1, value2, "codelevl");
            return (Criteria) this;
        }

        public Criteria andCodelevlNotBetween(String value1, String value2) {
            addCriterion("codelevl not between", value1, value2, "codelevl");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNull() {
            addCriterion("flags is null");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNotNull() {
            addCriterion("flags is not null");
            return (Criteria) this;
        }

        public Criteria andFlagsEqualTo(Short value) {
            addCriterion("flags =", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotEqualTo(Short value) {
            addCriterion("flags <>", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThan(Short value) {
            addCriterion("flags >", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThanOrEqualTo(Short value) {
            addCriterion("flags >=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThan(Short value) {
            addCriterion("flags <", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThanOrEqualTo(Short value) {
            addCriterion("flags <=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsIn(List<Short> values) {
            addCriterion("flags in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotIn(List<Short> values) {
            addCriterion("flags not in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsBetween(Short value1, Short value2) {
            addCriterion("flags between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotBetween(Short value1, Short value2) {
            addCriterion("flags not between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andLangname1IsNull() {
            addCriterion("langname1 is null");
            return (Criteria) this;
        }

        public Criteria andLangname1IsNotNull() {
            addCriterion("langname1 is not null");
            return (Criteria) this;
        }

        public Criteria andLangname1EqualTo(String value) {
            addCriterion("langname1 =", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1NotEqualTo(String value) {
            addCriterion("langname1 <>", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1GreaterThan(String value) {
            addCriterion("langname1 >", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1GreaterThanOrEqualTo(String value) {
            addCriterion("langname1 >=", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1LessThan(String value) {
            addCriterion("langname1 <", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1LessThanOrEqualTo(String value) {
            addCriterion("langname1 <=", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1Like(String value) {
            addCriterion("langname1 like", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1NotLike(String value) {
            addCriterion("langname1 not like", value, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1In(List<String> values) {
            addCriterion("langname1 in", values, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1NotIn(List<String> values) {
            addCriterion("langname1 not in", values, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1Between(String value1, String value2) {
            addCriterion("langname1 between", value1, value2, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname1NotBetween(String value1, String value2) {
            addCriterion("langname1 not between", value1, value2, "langname1");
            return (Criteria) this;
        }

        public Criteria andLangname2IsNull() {
            addCriterion("langname2 is null");
            return (Criteria) this;
        }

        public Criteria andLangname2IsNotNull() {
            addCriterion("langname2 is not null");
            return (Criteria) this;
        }

        public Criteria andLangname2EqualTo(String value) {
            addCriterion("langname2 =", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2NotEqualTo(String value) {
            addCriterion("langname2 <>", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2GreaterThan(String value) {
            addCriterion("langname2 >", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2GreaterThanOrEqualTo(String value) {
            addCriterion("langname2 >=", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2LessThan(String value) {
            addCriterion("langname2 <", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2LessThanOrEqualTo(String value) {
            addCriterion("langname2 <=", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2Like(String value) {
            addCriterion("langname2 like", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2NotLike(String value) {
            addCriterion("langname2 not like", value, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2In(List<String> values) {
            addCriterion("langname2 in", values, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2NotIn(List<String> values) {
            addCriterion("langname2 not in", values, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2Between(String value1, String value2) {
            addCriterion("langname2 between", value1, value2, "langname2");
            return (Criteria) this;
        }

        public Criteria andLangname2NotBetween(String value1, String value2) {
            addCriterion("langname2 not between", value1, value2, "langname2");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("bank is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("bank is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("bank =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("bank <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("bank >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("bank >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("bank <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("bank <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("bank like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("bank not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("bank in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("bank not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("bank between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("bank not between", value1, value2, "bank");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acode
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acode
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}