package com.snsoft.dao.entities;

import java.math.BigDecimal;
import java.util.Date;

public class Ccode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.ccode
     *
     * @mbg.generated
     */
    private String ccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.shortcode
     *
     * @mbg.generated
     */
    private String shortcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.fcodelist
     *
     * @mbg.generated
     */
    private String fcodelist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.ymdeprecated
     *
     * @mbg.generated
     */
    private Integer ymdeprecated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.modifydate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.levl
     *
     * @mbg.generated
     */
    private Byte levl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.langname1
     *
     * @mbg.generated
     */
    private String langname1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.langname2
     *
     * @mbg.generated
     */
    private String langname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.ecname
     *
     * @mbg.generated
     */
    private String ecname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.contact
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.mobil
     *
     * @mbg.generated
     */
    private String mobil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.httpurl
     *
     * @mbg.generated
     */
    private String httpurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.predate
     *
     * @mbg.generated
     */
    private Date predate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.submitdate
     *
     * @mbg.generated
     */
    private Date submitdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.assessflags
     *
     * @mbg.generated
     */
    private Byte assessflags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.submitdesc
     *
     * @mbg.generated
     */
    private String submitdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.submittelephone
     *
     * @mbg.generated
     */
    private String submittelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.submitwcode
     *
     * @mbg.generated
     */
    private String submitwcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.baccount
     *
     * @mbg.generated
     */
    private String baccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.creditvalue
     *
     * @mbg.generated
     */
    private BigDecimal creditvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.ncode
     *
     * @mbg.generated
     */
    private String ncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_1
     *
     * @mbg.generated
     */
    private String udf1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_2
     *
     * @mbg.generated
     */
    private String udf2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_3
     *
     * @mbg.generated
     */
    private String udf3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_4
     *
     * @mbg.generated
     */
    private String udf4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_5
     *
     * @mbg.generated
     */
    private String udf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_6
     *
     * @mbg.generated
     */
    private String udf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_7
     *
     * @mbg.generated
     */
    private String udf7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_8
     *
     * @mbg.generated
     */
    private String udf8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.udf_9
     *
     * @mbg.generated
     */
    private String udf9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.artno
     *
     * @mbg.generated
     */
    private String artno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.artperson
     *
     * @mbg.generated
     */
    private String artperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.taxno
     *
     * @mbg.generated
     */
    private String taxno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.allocdesc
     *
     * @mbg.generated
     */
    private String allocdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.sendaddress
     *
     * @mbg.generated
     */
    private String sendaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.partner
     *
     * @mbg.generated
     */
    private String partner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.rpbank
     *
     * @mbg.generated
     */
    private String rpbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.rpbankaccno
     *
     * @mbg.generated
     */
    private String rpbankaccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.ncodedesc
     *
     * @mbg.generated
     */
    private String ncodedesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.wl_flags
     *
     * @mbg.generated
     */
    private Integer wlFlags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.range
     *
     * @mbg.generated
     */
    private String range;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.gwcodes
     *
     * @mbg.generated
     */
    private String gwcodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.defbcode
     *
     * @mbg.generated
     */
    private String defbcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.matchup
     *
     * @mbg.generated
     */
    private String matchup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.sheetcode
     *
     * @mbg.generated
     */
    private String sheetcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.submitbcode
     *
     * @mbg.generated
     */
    private String submitbcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.inbcode
     *
     * @mbg.generated
     */
    private String inbcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccode.usedbcodestr
     *
     * @mbg.generated
     */
    private String usedbcodestr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.ccode
     *
     * @return the value of ccode.ccode
     *
     * @mbg.generated
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.ccode
     *
     * @param ccode the value for ccode.ccode
     *
     * @mbg.generated
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.cname
     *
     * @return the value of ccode.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.cname
     *
     * @param cname the value for ccode.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.shortcode
     *
     * @return the value of ccode.shortcode
     *
     * @mbg.generated
     */
    public String getShortcode() {
        return shortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.shortcode
     *
     * @param shortcode the value for ccode.shortcode
     *
     * @mbg.generated
     */
    public void setShortcode(String shortcode) {
        this.shortcode = shortcode == null ? null : shortcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.fcodelist
     *
     * @return the value of ccode.fcodelist
     *
     * @mbg.generated
     */
    public String getFcodelist() {
        return fcodelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.fcodelist
     *
     * @param fcodelist the value for ccode.fcodelist
     *
     * @mbg.generated
     */
    public void setFcodelist(String fcodelist) {
        this.fcodelist = fcodelist == null ? null : fcodelist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.ymdeprecated
     *
     * @return the value of ccode.ymdeprecated
     *
     * @mbg.generated
     */
    public Integer getYmdeprecated() {
        return ymdeprecated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.ymdeprecated
     *
     * @param ymdeprecated the value for ccode.ymdeprecated
     *
     * @mbg.generated
     */
    public void setYmdeprecated(Integer ymdeprecated) {
        this.ymdeprecated = ymdeprecated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.modifydate
     *
     * @return the value of ccode.modifydate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.modifydate
     *
     * @param modifydate the value for ccode.modifydate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.levl
     *
     * @return the value of ccode.levl
     *
     * @mbg.generated
     */
    public Byte getLevl() {
        return levl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.levl
     *
     * @param levl the value for ccode.levl
     *
     * @mbg.generated
     */
    public void setLevl(Byte levl) {
        this.levl = levl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.langname1
     *
     * @return the value of ccode.langname1
     *
     * @mbg.generated
     */
    public String getLangname1() {
        return langname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.langname1
     *
     * @param langname1 the value for ccode.langname1
     *
     * @mbg.generated
     */
    public void setLangname1(String langname1) {
        this.langname1 = langname1 == null ? null : langname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.langname2
     *
     * @return the value of ccode.langname2
     *
     * @mbg.generated
     */
    public String getLangname2() {
        return langname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.langname2
     *
     * @param langname2 the value for ccode.langname2
     *
     * @mbg.generated
     */
    public void setLangname2(String langname2) {
        this.langname2 = langname2 == null ? null : langname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.ecname
     *
     * @return the value of ccode.ecname
     *
     * @mbg.generated
     */
    public String getEcname() {
        return ecname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.ecname
     *
     * @param ecname the value for ccode.ecname
     *
     * @mbg.generated
     */
    public void setEcname(String ecname) {
        this.ecname = ecname == null ? null : ecname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.flag
     *
     * @return the value of ccode.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.flag
     *
     * @param flag the value for ccode.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.addr
     *
     * @return the value of ccode.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.addr
     *
     * @param addr the value for ccode.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.postcode
     *
     * @return the value of ccode.postcode
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.postcode
     *
     * @param postcode the value for ccode.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.contact
     *
     * @return the value of ccode.contact
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.contact
     *
     * @param contact the value for ccode.contact
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.telephone
     *
     * @return the value of ccode.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.telephone
     *
     * @param telephone the value for ccode.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.mobil
     *
     * @return the value of ccode.mobil
     *
     * @mbg.generated
     */
    public String getMobil() {
        return mobil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.mobil
     *
     * @param mobil the value for ccode.mobil
     *
     * @mbg.generated
     */
    public void setMobil(String mobil) {
        this.mobil = mobil == null ? null : mobil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.fax
     *
     * @return the value of ccode.fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.fax
     *
     * @param fax the value for ccode.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.email
     *
     * @return the value of ccode.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.email
     *
     * @param email the value for ccode.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.httpurl
     *
     * @return the value of ccode.httpurl
     *
     * @mbg.generated
     */
    public String getHttpurl() {
        return httpurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.httpurl
     *
     * @param httpurl the value for ccode.httpurl
     *
     * @mbg.generated
     */
    public void setHttpurl(String httpurl) {
        this.httpurl = httpurl == null ? null : httpurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.predate
     *
     * @return the value of ccode.predate
     *
     * @mbg.generated
     */
    public Date getPredate() {
        return predate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.predate
     *
     * @param predate the value for ccode.predate
     *
     * @mbg.generated
     */
    public void setPredate(Date predate) {
        this.predate = predate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.submitdate
     *
     * @return the value of ccode.submitdate
     *
     * @mbg.generated
     */
    public Date getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.submitdate
     *
     * @param submitdate the value for ccode.submitdate
     *
     * @mbg.generated
     */
    public void setSubmitdate(Date submitdate) {
        this.submitdate = submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.assessflags
     *
     * @return the value of ccode.assessflags
     *
     * @mbg.generated
     */
    public Byte getAssessflags() {
        return assessflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.assessflags
     *
     * @param assessflags the value for ccode.assessflags
     *
     * @mbg.generated
     */
    public void setAssessflags(Byte assessflags) {
        this.assessflags = assessflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.submitdesc
     *
     * @return the value of ccode.submitdesc
     *
     * @mbg.generated
     */
    public String getSubmitdesc() {
        return submitdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.submitdesc
     *
     * @param submitdesc the value for ccode.submitdesc
     *
     * @mbg.generated
     */
    public void setSubmitdesc(String submitdesc) {
        this.submitdesc = submitdesc == null ? null : submitdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.submittelephone
     *
     * @return the value of ccode.submittelephone
     *
     * @mbg.generated
     */
    public String getSubmittelephone() {
        return submittelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.submittelephone
     *
     * @param submittelephone the value for ccode.submittelephone
     *
     * @mbg.generated
     */
    public void setSubmittelephone(String submittelephone) {
        this.submittelephone = submittelephone == null ? null : submittelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.submitwcode
     *
     * @return the value of ccode.submitwcode
     *
     * @mbg.generated
     */
    public String getSubmitwcode() {
        return submitwcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.submitwcode
     *
     * @param submitwcode the value for ccode.submitwcode
     *
     * @mbg.generated
     */
    public void setSubmitwcode(String submitwcode) {
        this.submitwcode = submitwcode == null ? null : submitwcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.bank
     *
     * @return the value of ccode.bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.bank
     *
     * @param bank the value for ccode.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.baccount
     *
     * @return the value of ccode.baccount
     *
     * @mbg.generated
     */
    public String getBaccount() {
        return baccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.baccount
     *
     * @param baccount the value for ccode.baccount
     *
     * @mbg.generated
     */
    public void setBaccount(String baccount) {
        this.baccount = baccount == null ? null : baccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.creditvalue
     *
     * @return the value of ccode.creditvalue
     *
     * @mbg.generated
     */
    public BigDecimal getCreditvalue() {
        return creditvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.creditvalue
     *
     * @param creditvalue the value for ccode.creditvalue
     *
     * @mbg.generated
     */
    public void setCreditvalue(BigDecimal creditvalue) {
        this.creditvalue = creditvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.ncode
     *
     * @return the value of ccode.ncode
     *
     * @mbg.generated
     */
    public String getNcode() {
        return ncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.ncode
     *
     * @param ncode the value for ccode.ncode
     *
     * @mbg.generated
     */
    public void setNcode(String ncode) {
        this.ncode = ncode == null ? null : ncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_1
     *
     * @return the value of ccode.udf_1
     *
     * @mbg.generated
     */
    public String getUdf1() {
        return udf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_1
     *
     * @param udf1 the value for ccode.udf_1
     *
     * @mbg.generated
     */
    public void setUdf1(String udf1) {
        this.udf1 = udf1 == null ? null : udf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_2
     *
     * @return the value of ccode.udf_2
     *
     * @mbg.generated
     */
    public String getUdf2() {
        return udf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_2
     *
     * @param udf2 the value for ccode.udf_2
     *
     * @mbg.generated
     */
    public void setUdf2(String udf2) {
        this.udf2 = udf2 == null ? null : udf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_3
     *
     * @return the value of ccode.udf_3
     *
     * @mbg.generated
     */
    public String getUdf3() {
        return udf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_3
     *
     * @param udf3 the value for ccode.udf_3
     *
     * @mbg.generated
     */
    public void setUdf3(String udf3) {
        this.udf3 = udf3 == null ? null : udf3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_4
     *
     * @return the value of ccode.udf_4
     *
     * @mbg.generated
     */
    public String getUdf4() {
        return udf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_4
     *
     * @param udf4 the value for ccode.udf_4
     *
     * @mbg.generated
     */
    public void setUdf4(String udf4) {
        this.udf4 = udf4 == null ? null : udf4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_5
     *
     * @return the value of ccode.udf_5
     *
     * @mbg.generated
     */
    public String getUdf5() {
        return udf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_5
     *
     * @param udf5 the value for ccode.udf_5
     *
     * @mbg.generated
     */
    public void setUdf5(String udf5) {
        this.udf5 = udf5 == null ? null : udf5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_6
     *
     * @return the value of ccode.udf_6
     *
     * @mbg.generated
     */
    public String getUdf6() {
        return udf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_6
     *
     * @param udf6 the value for ccode.udf_6
     *
     * @mbg.generated
     */
    public void setUdf6(String udf6) {
        this.udf6 = udf6 == null ? null : udf6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_7
     *
     * @return the value of ccode.udf_7
     *
     * @mbg.generated
     */
    public String getUdf7() {
        return udf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_7
     *
     * @param udf7 the value for ccode.udf_7
     *
     * @mbg.generated
     */
    public void setUdf7(String udf7) {
        this.udf7 = udf7 == null ? null : udf7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_8
     *
     * @return the value of ccode.udf_8
     *
     * @mbg.generated
     */
    public String getUdf8() {
        return udf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_8
     *
     * @param udf8 the value for ccode.udf_8
     *
     * @mbg.generated
     */
    public void setUdf8(String udf8) {
        this.udf8 = udf8 == null ? null : udf8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.udf_9
     *
     * @return the value of ccode.udf_9
     *
     * @mbg.generated
     */
    public String getUdf9() {
        return udf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.udf_9
     *
     * @param udf9 the value for ccode.udf_9
     *
     * @mbg.generated
     */
    public void setUdf9(String udf9) {
        this.udf9 = udf9 == null ? null : udf9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.remark
     *
     * @return the value of ccode.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.remark
     *
     * @param remark the value for ccode.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.artno
     *
     * @return the value of ccode.artno
     *
     * @mbg.generated
     */
    public String getArtno() {
        return artno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.artno
     *
     * @param artno the value for ccode.artno
     *
     * @mbg.generated
     */
    public void setArtno(String artno) {
        this.artno = artno == null ? null : artno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.artperson
     *
     * @return the value of ccode.artperson
     *
     * @mbg.generated
     */
    public String getArtperson() {
        return artperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.artperson
     *
     * @param artperson the value for ccode.artperson
     *
     * @mbg.generated
     */
    public void setArtperson(String artperson) {
        this.artperson = artperson == null ? null : artperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.taxno
     *
     * @return the value of ccode.taxno
     *
     * @mbg.generated
     */
    public String getTaxno() {
        return taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.taxno
     *
     * @param taxno the value for ccode.taxno
     *
     * @mbg.generated
     */
    public void setTaxno(String taxno) {
        this.taxno = taxno == null ? null : taxno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.allocdesc
     *
     * @return the value of ccode.allocdesc
     *
     * @mbg.generated
     */
    public String getAllocdesc() {
        return allocdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.allocdesc
     *
     * @param allocdesc the value for ccode.allocdesc
     *
     * @mbg.generated
     */
    public void setAllocdesc(String allocdesc) {
        this.allocdesc = allocdesc == null ? null : allocdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.sendaddress
     *
     * @return the value of ccode.sendaddress
     *
     * @mbg.generated
     */
    public String getSendaddress() {
        return sendaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.sendaddress
     *
     * @param sendaddress the value for ccode.sendaddress
     *
     * @mbg.generated
     */
    public void setSendaddress(String sendaddress) {
        this.sendaddress = sendaddress == null ? null : sendaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.partner
     *
     * @return the value of ccode.partner
     *
     * @mbg.generated
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.partner
     *
     * @param partner the value for ccode.partner
     *
     * @mbg.generated
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.status
     *
     * @return the value of ccode.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.status
     *
     * @param status the value for ccode.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.rpbank
     *
     * @return the value of ccode.rpbank
     *
     * @mbg.generated
     */
    public String getRpbank() {
        return rpbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.rpbank
     *
     * @param rpbank the value for ccode.rpbank
     *
     * @mbg.generated
     */
    public void setRpbank(String rpbank) {
        this.rpbank = rpbank == null ? null : rpbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.rpbankaccno
     *
     * @return the value of ccode.rpbankaccno
     *
     * @mbg.generated
     */
    public String getRpbankaccno() {
        return rpbankaccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.rpbankaccno
     *
     * @param rpbankaccno the value for ccode.rpbankaccno
     *
     * @mbg.generated
     */
    public void setRpbankaccno(String rpbankaccno) {
        this.rpbankaccno = rpbankaccno == null ? null : rpbankaccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.ncodedesc
     *
     * @return the value of ccode.ncodedesc
     *
     * @mbg.generated
     */
    public String getNcodedesc() {
        return ncodedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.ncodedesc
     *
     * @param ncodedesc the value for ccode.ncodedesc
     *
     * @mbg.generated
     */
    public void setNcodedesc(String ncodedesc) {
        this.ncodedesc = ncodedesc == null ? null : ncodedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.wl_flags
     *
     * @return the value of ccode.wl_flags
     *
     * @mbg.generated
     */
    public Integer getWlFlags() {
        return wlFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.wl_flags
     *
     * @param wlFlags the value for ccode.wl_flags
     *
     * @mbg.generated
     */
    public void setWlFlags(Integer wlFlags) {
        this.wlFlags = wlFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.range
     *
     * @return the value of ccode.range
     *
     * @mbg.generated
     */
    public String getRange() {
        return range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.range
     *
     * @param range the value for ccode.range
     *
     * @mbg.generated
     */
    public void setRange(String range) {
        this.range = range == null ? null : range.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.gwcodes
     *
     * @return the value of ccode.gwcodes
     *
     * @mbg.generated
     */
    public String getGwcodes() {
        return gwcodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.gwcodes
     *
     * @param gwcodes the value for ccode.gwcodes
     *
     * @mbg.generated
     */
    public void setGwcodes(String gwcodes) {
        this.gwcodes = gwcodes == null ? null : gwcodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.password
     *
     * @return the value of ccode.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.password
     *
     * @param password the value for ccode.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.defbcode
     *
     * @return the value of ccode.defbcode
     *
     * @mbg.generated
     */
    public String getDefbcode() {
        return defbcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.defbcode
     *
     * @param defbcode the value for ccode.defbcode
     *
     * @mbg.generated
     */
    public void setDefbcode(String defbcode) {
        this.defbcode = defbcode == null ? null : defbcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.matchup
     *
     * @return the value of ccode.matchup
     *
     * @mbg.generated
     */
    public String getMatchup() {
        return matchup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.matchup
     *
     * @param matchup the value for ccode.matchup
     *
     * @mbg.generated
     */
    public void setMatchup(String matchup) {
        this.matchup = matchup == null ? null : matchup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.sheetcode
     *
     * @return the value of ccode.sheetcode
     *
     * @mbg.generated
     */
    public String getSheetcode() {
        return sheetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.sheetcode
     *
     * @param sheetcode the value for ccode.sheetcode
     *
     * @mbg.generated
     */
    public void setSheetcode(String sheetcode) {
        this.sheetcode = sheetcode == null ? null : sheetcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.submitbcode
     *
     * @return the value of ccode.submitbcode
     *
     * @mbg.generated
     */
    public String getSubmitbcode() {
        return submitbcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.submitbcode
     *
     * @param submitbcode the value for ccode.submitbcode
     *
     * @mbg.generated
     */
    public void setSubmitbcode(String submitbcode) {
        this.submitbcode = submitbcode == null ? null : submitbcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.inbcode
     *
     * @return the value of ccode.inbcode
     *
     * @mbg.generated
     */
    public String getInbcode() {
        return inbcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.inbcode
     *
     * @param inbcode the value for ccode.inbcode
     *
     * @mbg.generated
     */
    public void setInbcode(String inbcode) {
        this.inbcode = inbcode == null ? null : inbcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccode.usedbcodestr
     *
     * @return the value of ccode.usedbcodestr
     *
     * @mbg.generated
     */
    public String getUsedbcodestr() {
        return usedbcodestr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccode.usedbcodestr
     *
     * @param usedbcodestr the value for ccode.usedbcodestr
     *
     * @mbg.generated
     */
    public void setUsedbcodestr(String usedbcodestr) {
        this.usedbcodestr = usedbcodestr == null ? null : usedbcodestr.trim();
    }
}