package com.snsoft.dao.entities;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Company.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Company.CompanyCode
     *
     * @mbg.generated
     */
    private String companycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Company.CompanyName
     *
     * @mbg.generated
     */
    private String companyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Company.Id
     *
     * @return the value of Company.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Company.Id
     *
     * @param id the value for Company.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Company.CompanyCode
     *
     * @return the value of Company.CompanyCode
     *
     * @mbg.generated
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Company.CompanyCode
     *
     * @param companycode the value for Company.CompanyCode
     *
     * @mbg.generated
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode == null ? null : companycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Company.CompanyName
     *
     * @return the value of Company.CompanyName
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Company.CompanyName
     *
     * @param companyname the value for Company.CompanyName
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }
}