package com.snsoft.dao.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DetonatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public DetonatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChipidIsNull() {
            addCriterion("ChipId is null");
            return (Criteria) this;
        }

        public Criteria andChipidIsNotNull() {
            addCriterion("ChipId is not null");
            return (Criteria) this;
        }

        public Criteria andChipidEqualTo(String value) {
            addCriterion("ChipId =", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidNotEqualTo(String value) {
            addCriterion("ChipId <>", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidGreaterThan(String value) {
            addCriterion("ChipId >", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidGreaterThanOrEqualTo(String value) {
            addCriterion("ChipId >=", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidLessThan(String value) {
            addCriterion("ChipId <", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidLessThanOrEqualTo(String value) {
            addCriterion("ChipId <=", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidLike(String value) {
            addCriterion("ChipId like", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidNotLike(String value) {
            addCriterion("ChipId not like", value, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidIn(List<String> values) {
            addCriterion("ChipId in", values, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidNotIn(List<String> values) {
            addCriterion("ChipId not in", values, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidBetween(String value1, String value2) {
            addCriterion("ChipId between", value1, value2, "chipid");
            return (Criteria) this;
        }

        public Criteria andChipidNotBetween(String value1, String value2) {
            addCriterion("ChipId not between", value1, value2, "chipid");
            return (Criteria) this;
        }

        public Criteria andShellcodeIsNull() {
            addCriterion("ShellCode is null");
            return (Criteria) this;
        }

        public Criteria andShellcodeIsNotNull() {
            addCriterion("ShellCode is not null");
            return (Criteria) this;
        }

        public Criteria andShellcodeEqualTo(String value) {
            addCriterion("ShellCode =", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeNotEqualTo(String value) {
            addCriterion("ShellCode <>", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeGreaterThan(String value) {
            addCriterion("ShellCode >", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ShellCode >=", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeLessThan(String value) {
            addCriterion("ShellCode <", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeLessThanOrEqualTo(String value) {
            addCriterion("ShellCode <=", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeLike(String value) {
            addCriterion("ShellCode like", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeNotLike(String value) {
            addCriterion("ShellCode not like", value, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeIn(List<String> values) {
            addCriterion("ShellCode in", values, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeNotIn(List<String> values) {
            addCriterion("ShellCode not in", values, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeBetween(String value1, String value2) {
            addCriterion("ShellCode between", value1, value2, "shellcode");
            return (Criteria) this;
        }

        public Criteria andShellcodeNotBetween(String value1, String value2) {
            addCriterion("ShellCode not between", value1, value2, "shellcode");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(Integer value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(Integer value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(Integer value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(Integer value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(Integer value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(Integer value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<Integer> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<Integer> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(Integer value1, Integer value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(Integer value1, Integer value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("Uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("Uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("Uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("Uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("Uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("Uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("Uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("Uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("Uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("Uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("Uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("Uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("Uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("Uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andCodingdateIsNull() {
            addCriterion("CodingDate is null");
            return (Criteria) this;
        }

        public Criteria andCodingdateIsNotNull() {
            addCriterion("CodingDate is not null");
            return (Criteria) this;
        }

        public Criteria andCodingdateEqualTo(Date value) {
            addCriterion("CodingDate =", value, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateNotEqualTo(Date value) {
            addCriterion("CodingDate <>", value, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateGreaterThan(Date value) {
            addCriterion("CodingDate >", value, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateGreaterThanOrEqualTo(Date value) {
            addCriterion("CodingDate >=", value, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateLessThan(Date value) {
            addCriterion("CodingDate <", value, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateLessThanOrEqualTo(Date value) {
            addCriterion("CodingDate <=", value, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateIn(List<Date> values) {
            addCriterion("CodingDate in", values, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateNotIn(List<Date> values) {
            addCriterion("CodingDate not in", values, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateBetween(Date value1, Date value2) {
            addCriterion("CodingDate between", value1, value2, "codingdate");
            return (Criteria) this;
        }

        public Criteria andCodingdateNotBetween(Date value1, Date value2) {
            addCriterion("CodingDate not between", value1, value2, "codingdate");
            return (Criteria) this;
        }

        public Criteria andFootlengthIsNull() {
            addCriterion("FootLength is null");
            return (Criteria) this;
        }

        public Criteria andFootlengthIsNotNull() {
            addCriterion("FootLength is not null");
            return (Criteria) this;
        }

        public Criteria andFootlengthEqualTo(Integer value) {
            addCriterion("FootLength =", value, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthNotEqualTo(Integer value) {
            addCriterion("FootLength <>", value, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthGreaterThan(Integer value) {
            addCriterion("FootLength >", value, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("FootLength >=", value, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthLessThan(Integer value) {
            addCriterion("FootLength <", value, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthLessThanOrEqualTo(Integer value) {
            addCriterion("FootLength <=", value, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthIn(List<Integer> values) {
            addCriterion("FootLength in", values, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthNotIn(List<Integer> values) {
            addCriterion("FootLength not in", values, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthBetween(Integer value1, Integer value2) {
            addCriterion("FootLength between", value1, value2, "footlength");
            return (Criteria) this;
        }

        public Criteria andFootlengthNotBetween(Integer value1, Integer value2) {
            addCriterion("FootLength not between", value1, value2, "footlength");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNull() {
            addCriterion("Platform is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNotNull() {
            addCriterion("Platform is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformEqualTo(Integer value) {
            addCriterion("Platform =", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotEqualTo(Integer value) {
            addCriterion("Platform <>", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThan(Integer value) {
            addCriterion("Platform >", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThanOrEqualTo(Integer value) {
            addCriterion("Platform >=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThan(Integer value) {
            addCriterion("Platform <", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThanOrEqualTo(Integer value) {
            addCriterion("Platform <=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformIn(List<Integer> values) {
            addCriterion("Platform in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotIn(List<Integer> values) {
            addCriterion("Platform not in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformBetween(Integer value1, Integer value2) {
            addCriterion("Platform between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotBetween(Integer value1, Integer value2) {
            addCriterion("Platform not between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andClientIsNull() {
            addCriterion("Client is null");
            return (Criteria) this;
        }

        public Criteria andClientIsNotNull() {
            addCriterion("Client is not null");
            return (Criteria) this;
        }

        public Criteria andClientEqualTo(String value) {
            addCriterion("Client =", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotEqualTo(String value) {
            addCriterion("Client <>", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientGreaterThan(String value) {
            addCriterion("Client >", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientGreaterThanOrEqualTo(String value) {
            addCriterion("Client >=", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLessThan(String value) {
            addCriterion("Client <", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLessThanOrEqualTo(String value) {
            addCriterion("Client <=", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLike(String value) {
            addCriterion("Client like", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotLike(String value) {
            addCriterion("Client not like", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientIn(List<String> values) {
            addCriterion("Client in", values, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotIn(List<String> values) {
            addCriterion("Client not in", values, "client");
            return (Criteria) this;
        }

        public Criteria andClientBetween(String value1, String value2) {
            addCriterion("Client between", value1, value2, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotBetween(String value1, String value2) {
            addCriterion("Client not between", value1, value2, "client");
            return (Criteria) this;
        }

        public Criteria andUploadstatusIsNull() {
            addCriterion("UploadStatus is null");
            return (Criteria) this;
        }

        public Criteria andUploadstatusIsNotNull() {
            addCriterion("UploadStatus is not null");
            return (Criteria) this;
        }

        public Criteria andUploadstatusEqualTo(Integer value) {
            addCriterion("UploadStatus =", value, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusNotEqualTo(Integer value) {
            addCriterion("UploadStatus <>", value, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusGreaterThan(Integer value) {
            addCriterion("UploadStatus >", value, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("UploadStatus >=", value, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusLessThan(Integer value) {
            addCriterion("UploadStatus <", value, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusLessThanOrEqualTo(Integer value) {
            addCriterion("UploadStatus <=", value, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusIn(List<Integer> values) {
            addCriterion("UploadStatus in", values, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusNotIn(List<Integer> values) {
            addCriterion("UploadStatus not in", values, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusBetween(Integer value1, Integer value2) {
            addCriterion("UploadStatus between", value1, value2, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploadstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("UploadStatus not between", value1, value2, "uploadstatus");
            return (Criteria) this;
        }

        public Criteria andUploaddateIsNull() {
            addCriterion("UploadDate is null");
            return (Criteria) this;
        }

        public Criteria andUploaddateIsNotNull() {
            addCriterion("UploadDate is not null");
            return (Criteria) this;
        }

        public Criteria andUploaddateEqualTo(Date value) {
            addCriterion("UploadDate =", value, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateNotEqualTo(Date value) {
            addCriterion("UploadDate <>", value, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateGreaterThan(Date value) {
            addCriterion("UploadDate >", value, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateGreaterThanOrEqualTo(Date value) {
            addCriterion("UploadDate >=", value, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateLessThan(Date value) {
            addCriterion("UploadDate <", value, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateLessThanOrEqualTo(Date value) {
            addCriterion("UploadDate <=", value, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateIn(List<Date> values) {
            addCriterion("UploadDate in", values, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateNotIn(List<Date> values) {
            addCriterion("UploadDate not in", values, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateBetween(Date value1, Date value2) {
            addCriterion("UploadDate between", value1, value2, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andUploaddateNotBetween(Date value1, Date value2) {
            addCriterion("UploadDate not between", value1, value2, "uploaddate");
            return (Criteria) this;
        }

        public Criteria andPackagestatusIsNull() {
            addCriterion("PackageStatus is null");
            return (Criteria) this;
        }

        public Criteria andPackagestatusIsNotNull() {
            addCriterion("PackageStatus is not null");
            return (Criteria) this;
        }

        public Criteria andPackagestatusEqualTo(Integer value) {
            addCriterion("PackageStatus =", value, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusNotEqualTo(Integer value) {
            addCriterion("PackageStatus <>", value, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusGreaterThan(Integer value) {
            addCriterion("PackageStatus >", value, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("PackageStatus >=", value, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusLessThan(Integer value) {
            addCriterion("PackageStatus <", value, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusLessThanOrEqualTo(Integer value) {
            addCriterion("PackageStatus <=", value, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusIn(List<Integer> values) {
            addCriterion("PackageStatus in", values, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusNotIn(List<Integer> values) {
            addCriterion("PackageStatus not in", values, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusBetween(Integer value1, Integer value2) {
            addCriterion("PackageStatus between", value1, value2, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andPackagestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("PackageStatus not between", value1, value2, "packagestatus");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CreateDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CreateDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CreateDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CreateDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CreateDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CreateDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CreateDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CreateDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CreateDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("UserName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("UserName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("UserName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("UserName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("UserName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("UserName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("UserName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("UserName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("UserName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("UserName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("UserName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("UserName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("UserName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("UserName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("Created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("Created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("Created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("Created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("Created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("Created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("Created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("Created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("Created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("Created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("Created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("Created not between", value1, value2, "created");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Detonator
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}