package com.snsoft.dao.entities;

import java.util.Date;

public class Detonator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.Id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.ChipId
     *
     * @mbg.generated
     */
    private String chipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.ShellCode
     *
     * @mbg.generated
     */
    private String shellcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.Password
     *
     * @mbg.generated
     */
    private Integer password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.CodingDate
     *
     * @mbg.generated
     */
    private Date codingdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.FootLength
     *
     * @mbg.generated
     */
    private Integer footlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.Platform
     *
     * @mbg.generated
     */
    private Integer platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.Client
     *
     * @mbg.generated
     */
    private String client;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.UploadStatus
     *
     * @mbg.generated
     */
    private Integer uploadstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.UploadDate
     *
     * @mbg.generated
     */
    private Date uploaddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.PackageStatus
     *
     * @mbg.generated
     */
    private Integer packagestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.CreateDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detonator.Created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.Id
     *
     * @return the value of Detonator.Id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.Id
     *
     * @param id the value for Detonator.Id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.ChipId
     *
     * @return the value of Detonator.ChipId
     *
     * @mbg.generated
     */
    public String getChipid() {
        return chipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.ChipId
     *
     * @param chipid the value for Detonator.ChipId
     *
     * @mbg.generated
     */
    public void setChipid(String chipid) {
        this.chipid = chipid == null ? null : chipid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.ShellCode
     *
     * @return the value of Detonator.ShellCode
     *
     * @mbg.generated
     */
    public String getShellcode() {
        return shellcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.ShellCode
     *
     * @param shellcode the value for Detonator.ShellCode
     *
     * @mbg.generated
     */
    public void setShellcode(String shellcode) {
        this.shellcode = shellcode == null ? null : shellcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.Password
     *
     * @return the value of Detonator.Password
     *
     * @mbg.generated
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.Password
     *
     * @param password the value for Detonator.Password
     *
     * @mbg.generated
     */
    public void setPassword(Integer password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.Uid
     *
     * @return the value of Detonator.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.Uid
     *
     * @param uid the value for Detonator.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.CodingDate
     *
     * @return the value of Detonator.CodingDate
     *
     * @mbg.generated
     */
    public Date getCodingdate() {
        return codingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.CodingDate
     *
     * @param codingdate the value for Detonator.CodingDate
     *
     * @mbg.generated
     */
    public void setCodingdate(Date codingdate) {
        this.codingdate = codingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.FootLength
     *
     * @return the value of Detonator.FootLength
     *
     * @mbg.generated
     */
    public Integer getFootlength() {
        return footlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.FootLength
     *
     * @param footlength the value for Detonator.FootLength
     *
     * @mbg.generated
     */
    public void setFootlength(Integer footlength) {
        this.footlength = footlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.Platform
     *
     * @return the value of Detonator.Platform
     *
     * @mbg.generated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.Platform
     *
     * @param platform the value for Detonator.Platform
     *
     * @mbg.generated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.Client
     *
     * @return the value of Detonator.Client
     *
     * @mbg.generated
     */
    public String getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.Client
     *
     * @param client the value for Detonator.Client
     *
     * @mbg.generated
     */
    public void setClient(String client) {
        this.client = client == null ? null : client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.UploadStatus
     *
     * @return the value of Detonator.UploadStatus
     *
     * @mbg.generated
     */
    public Integer getUploadstatus() {
        return uploadstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.UploadStatus
     *
     * @param uploadstatus the value for Detonator.UploadStatus
     *
     * @mbg.generated
     */
    public void setUploadstatus(Integer uploadstatus) {
        this.uploadstatus = uploadstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.UploadDate
     *
     * @return the value of Detonator.UploadDate
     *
     * @mbg.generated
     */
    public Date getUploaddate() {
        return uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.UploadDate
     *
     * @param uploaddate the value for Detonator.UploadDate
     *
     * @mbg.generated
     */
    public void setUploaddate(Date uploaddate) {
        this.uploaddate = uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.PackageStatus
     *
     * @return the value of Detonator.PackageStatus
     *
     * @mbg.generated
     */
    public Integer getPackagestatus() {
        return packagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.PackageStatus
     *
     * @param packagestatus the value for Detonator.PackageStatus
     *
     * @mbg.generated
     */
    public void setPackagestatus(Integer packagestatus) {
        this.packagestatus = packagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.CreateDate
     *
     * @return the value of Detonator.CreateDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.CreateDate
     *
     * @param createdate the value for Detonator.CreateDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.UserName
     *
     * @return the value of Detonator.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.UserName
     *
     * @param username the value for Detonator.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detonator.Created
     *
     * @return the value of Detonator.Created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detonator.Created
     *
     * @param created the value for Detonator.Created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}