package com.snsoft.dao.mappers;

import com.snsoft.dao.entities.Acode;
import com.snsoft.dao.entities.AcodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    long countByExample(AcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int deleteByExample(AcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String acode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int insert(Acode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int insertSelective(Acode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    List<Acode> selectByExample(AcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    Acode selectByPrimaryKey(String acode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Acode record, @Param("example") AcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Acode record, @Param("example") AcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Acode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acode
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Acode record);
}