package com.snsoft.dao.mappers;

import com.snsoft.dao.entities.Detonator;
import com.snsoft.dao.entities.DetonatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetonatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    long countByExample(DetonatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int deleteByExample(DetonatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int insert(Detonator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int insertSelective(Detonator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    List<Detonator> selectByExample(DetonatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    Detonator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Detonator record, @Param("example") DetonatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Detonator record, @Param("example") DetonatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Detonator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detonator
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Detonator record);
}